# Generated by Django 5.2.4 on 2025-08-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='category_type',
            field=models.CharField(choices=[('Consumable', 'Consumable'), ('Mass', 'Mass Product'), ('Quantity', 'Quantity Product'), ('Normal', 'Normal Product')], default='Normal Product', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='product_name',
            field=models.CharField(default='normal product', max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='product',
        ),
    ]
