# Generated by Django 5.2.4 on 2025-08-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_address_alter_supplier_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='delivery_days',
            new_name='email',
        ),
    ]
