# Generated by Django 5.2.4 on 2025-08-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplierproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='category_type',
            field=models.CharField(choices=[('Consumable', 'Consumable'), ('Mass Product', 'Mass Product'), ('Quantity Product', 'Quantity Product'), ('Normal Product', 'Normal Product')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supplier.supplier'),
        ),
    ]
