# Generated by Django 5.2.4 on 2025-08-30 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplierproduct_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='supplier.supplier'),
        ),
    ]
