# Generated by Django 5.2.4 on 2025-08-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_supplier_payment_terms_supplierorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='SupplierOrder',
        ),
    ]
