# Generated by Django 5.2.4 on 2025-08-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_supplier_payment_terms_delete_supplierorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='payment_terms',
            new_name='product',
        ),
        migrations.AddField(
            model_name='supplier',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
