# Generated by Django 5.2.4 on 2025-08-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_rename_payment_terms_supplier_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='stock_price',
            field=models.FloatField(default=0),
        ),
    ]
