# Generated by Django 5.2.4 on 2025-08-24 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_supplier_total_alter_supplier_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='stock_price',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='total',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supplier.category')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_price', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='supplier.supplier')),
            ],
        ),
    ]
