# Generated by Django 5.2.4 on 2025-08-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0004_alter_supplierproduct_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Consumable', 'Consumable'), ('Mass Product', 'Mass Product'), ('Quantity Product', 'Quantity Product'), ('Normal Product', 'Normal Product')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='supplier.supplierproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RawMaterialUsage',
        ),
    ]
