# Generated by Django 5.2.4 on 2025-08-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_category_type_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Consumable', 'Consumable'), ('Mass Product', 'Mass Product'), ('Quantity Product', 'Quantity Product'), ('Normal Product', 'Normal Product')], max_length=50, null=True),
        ),
    ]
