# Generated by Django 5.2.5 on 2025-08-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_name',
            new_name='shop_name',
        ),
    ]
