# Generated by Django 5.2.5 on 2025-08-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authication', '0002_rename_company_name_profile_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
