# Generated by Django 5.2.4 on 2025-08-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authication', '0004_remove_profile_company_name_profile_shop_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
